In [2]:
import numpy as np

def arredondar(num, sig=6):
    """Arredonda um número para um número fixo de algarismos significativos."""
    if num == 0:
        return 0.0
    else:
        return float(f"{num:.{sig}g}")

def arredondar_matriz(mat, sig=6):
    """Aplica arredondamento a todos os elementos de uma matriz."""
    return np.vectorize(lambda x: arredondar(x, sig))(mat)

def substituicao_regressiva(Ab, sig=6):
    """Executa substituição regressiva para resolver o sistema triangular superior."""
    n = len(Ab)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        soma = sum(arredondar(Ab[i, j] * x[j], sig) for j in range(i+1, n))
        x[i] = arredondar((Ab[i, -1] - soma) / Ab[i, i], sig)
        print(f"\n🔻 Substituição regressiva para x{i+1}: {x[i]:.8f}")
    return x

def eliminacao_gauss_pivotamento(A, b, sig=6):
    """Executa a Eliminação de Gauss com pivotamento parcial e imprime cada passo."""
    n = len(A)
    Ab = np.hstack((A, b.reshape(-1, 1)))  # Matriz aumentada

    print("\n🔢 Matriz aumentada inicial:")
    print(arredondar_matriz(Ab, sig))

    # Eliminação com pivotamento parcial
    for i in range(n):
        print(f"\n🔄 Passo {i+1} - Início da iteração")

        # Pivotamento parcial
        max_idx = np.argmax(np.abs(Ab[i:, i])) + i
        if i != max_idx:
            Ab[[i, max_idx]] = Ab[[max_idx, i]]
            print(f"\n🔁 Trocando linha {i+1} com linha {max_idx+1} (pivotamento parcial):")
            print(arredondar_matriz(Ab, sig))
        else:
            print(f"\n🔁 Nenhuma troca de linhas necessária.")

        # Eliminação de Gauss (para zerar abaixo do pivô)
        for j in range(i+1, n):
            if Ab[i, i] == 0:
                print(f"⚠️ Pivô nulo na linha {i+1}, não é possível continuar.")
                continue
            fator = arredondar(Ab[j, i] / Ab[i, i], sig)
            print(f"\n🔨 Calculando fator de eliminação: {fator} para a linha {j+1}")

            for k in range(i, n+1):
                Ab[j, k] = arredondar(Ab[j, k] - fator * Ab[i, k], sig)

            print(f"\n📊 Após eliminação da linha {j+1}:")
            print(arredondar_matriz(Ab, sig))

    print("\n📐 Matriz triangular superior:")
    print(arredondar_matriz(Ab, sig))

    # Substituição regressiva
    x = substituicao_regressiva(Ab, sig)

    print("\n✅ Solução final (com 8 casas decimais):")
    for i, valor in enumerate(x, 1):
        print(f"x{i} = {valor:.8f}")

    return x

def entrada_usuario():
    """Faz a entrada interativa da matriz e vetor."""
    try:
        tamanho = input("Digite o tamanho da matriz no formato 'nxn' (ex: 3x3): ").lower().strip()
        n = int(tamanho.split('x')[0])

        A = np.zeros((n, n))
        b = np.zeros(n)

        print("\n📥 Preenchendo a matriz A (coeficientes do sistema):")
        for i in range(n):
            for j in range(n):
                A[i, j] = float(input(f"  a{i+1}{j+1} = "))

        print("\n📥 Preenchendo o vetor b (termos independentes):")
        for i in range(n):
            b[i] = float(input(f"  b{i+1} = "))

        return A, b

    except Exception as e:
        print(f"\n❌ Erro de entrada: {e}")
        return None, None

# Execução principal
A, b = entrada_usuario()
if A is not None and b is not None:
    eliminacao_gauss_pivotamento(A, b, sig=6)


Digite o tamanho da matriz no formato 'nxn' (ex: 3x3): 3

📥 Preenchendo a matriz A (coeficientes do sistema):
  a11 = 10
  a12 = 1
  a13 = 1
  a21 = 1
  a22 = 10
  a23 = 1
  a31 = 1
  a32 = 1
  a33 = 10

📥 Preenchendo o vetor b (termos independentes):
  b1 = 12
  b2 = 12
  b3 = 12

🔢 Matriz aumentada inicial:
[[10.  1.  1. 12.]
 [ 1. 10.  1. 12.]
 [ 1.  1. 10. 12.]]

🔄 Passo 1 - Início da iteração

🔁 Nenhuma troca de linhas necessária.

🔨 Calculando fator de eliminação: 0.1 para a linha 2

📊 Após eliminação da linha 2:
[[10.   1.   1.  12. ]
 [ 0.   9.9  0.9 10.8]
 [ 1.   1.  10.  12. ]]

🔨 Calculando fator de eliminação: 0.1 para a linha 3

📊 Após eliminação da linha 3:
[[10.   1.   1.  12. ]
 [ 0.   9.9  0.9 10.8]
 [ 0.   0.9  9.9 10.8]]

🔄 Passo 2 - Início da iteração

🔁 Nenhuma troca de linhas necessária.

🔨 Calculando fator de eliminação: 0.0909091 para a linha 3

📊 Após eliminação da linha 3:
[[ 1.00000e+01  1.00000e+00  1.00000e+00  1.20000e+01]
 [ 0.00000e+00  9.90000e+00  9.00